In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
data = pd.read_csv('anime-dataset-2023.csv')
# Display the first few rows of the dataset
print(data.head())
# Check for missing values
print(data.isnull().sum())

   anime_id                             Name             English name  \
0         1                     Cowboy Bebop             Cowboy Bebop
1         5  Cowboy Bebop: Tengoku no Tobira  Cowboy Bebop: The Movie
2         6                           Trigun                   Trigun
3         7               Witch Hunter Robin       Witch Hunter Robin
4         8                   Bouken Ou Beet   Beet the Vandel Buster

                         Other name Score  \
0                         カウボーイビバップ  8.75
1                    カウボーイビバップ 天国の扉  8.38
2                             トライガン  8.22
3  Witch Hunter ROBIN (ウイッチハンターロビン)  7.25
4                            冒険王ビィト  6.94

                                 Genres  \
0         Action, Award Winning, Sci-Fi
1                        Action, Sci-Fi
2             Action, Adventure, Sci-Fi
3  Action, Drama, Mystery, Supernatural
4      Adventure, Fantasy, Supernatural

                                            Synopsis   Type Episodes  \
0  Crime is timeless. By the year 2071, humanity ...     TV       26
1  Another day, another bounty—such is the life o...  Movie        1
2  Vash the Stampede is the man with a $$60,000,0...     TV       26
3  Robin Sena is a powerful craft user drafted in...     TV       26
4  It is the dark century and the people are suff...     TV       52

                          Aired  ...         Studios    Source       Duration  \
0   Apr 3, 1998 to Apr 24, 1999  ...         Sunrise  Original  24 min per ep
1                   Sep 1, 2001  ...           Bones  Original    1 hr 55 min
2   Apr 1, 1998 to Sep 30, 1998  ...        Madhouse     Manga  24 min per ep
3   Jul 3, 2002 to Dec 25, 2002  ...         Sunrise  Original  25 min per ep
4  Sep 30, 2004 to Sep 29, 2005  ...  Toei Animation     Manga  23 min per ep

                           Rating  Rank Popularity Favorites Scored By  \
0  R - 17+ (violence & profanity)    41         43     78525    914193
1  R - 17+ (violence & profanity)   189        602      1448    206248
2       PG-13 - Teens 13 or older   328        246     15035    356739
3       PG-13 - Teens 13 or older  2764       1795       613     42829
4                   PG - Children  4240       5126        14      6413

   Members                                          Image URL
0  1771505  https://cdn.myanimelist.net/images/anime/4/196...
1   360978  https://cdn.myanimelist.net/images/anime/1439/...
2   727252  https://cdn.myanimelist.net/images/anime/7/203...
3   111931  https://cdn.myanimelist.net/images/anime/10/19...
4    15001  https://cdn.myanimelist.net/images/anime/7/215...

[5 rows x 24 columns]
anime_id        0
Name            0
English name    0
Other name      0
Score           0
Genres          0
Synopsis        0
Type            0
Episodes        0
Aired           0
Premiered       0
Status          0
Producers       0
Licensors       0
Studios         0
Source          0
Duration        0
Rating          0
Rank            0
Popularity      0
Favorites       0
Scored By       0
Members         0
Image URL       0
dtype: int64

In [3]:
data["Episodes"] = data["Episodes"].replace("UNKNOWN", 0)
data["Episodes"] = data["Episodes"].astype(int)

In [4]:
data["Episodes"][11]

np.int64(0)

In [5]:
data.query("Score=='UNKNOWN'")

,anime_id,Name,English name,Other name,Score,Genres,Synopsis,Type,Episodes,Aired,...,Studios,Source,Duration,Rating,Rank,Popularity,Favorites,Scored By,Members,Image URL
1578,1739,Shibawanko no Wa no Kokoro,UNKNOWN,しばわんこの和のこころ,UNKNOWN,UNKNOWN,Based on a japanese children`s book by Yoshie ...,TV,80,"Apr 5, 2006 to Mar 14, 2007",...,Three-d,Unknown,2 min per ep,G - All Ages,19660,13679,1,UNKNOWN,728,https://cdn.myanimelist.net/images/anime/11/70...
1699,1863,Silk Road Shounen Yuuto,UNKNOWN,シルクロード少年 ユート,UNKNOWN,"Adventure, Fantasy","When a boy Yuto visits Qinghai in China, he is...",TV,26,"Sep 16, 2006 to Mar 24, 2007",...,OLM,Unknown,20 min per ep,UNKNOWN,19912,13981,0,UNKNOWN,657,https://cdn.myanimelist.net/images/anime/1/186...
2476,2701,Susie-chan to Marvy,Little Susie and Marvy,スージーちゃんとマービー,UNKNOWN,Comedy,No description available for this anime.,TV,104,"Apr 5, 1999 to Feb 3, 2000",...,Xebec,Unknown,15 min per ep,UNKNOWN,12706,16212,0,UNKNOWN,374,https://cdn.myanimelist.net/images/anime/10/36...
2483,2708,Wankorobee,UNKNOWN,わんころべえ,UNKNOWN,"Comedy, Fantasy",No description available for this anime.,TV,26,"Oct 6, 1996 to Mar 30, 1997",...,"Ajia-do, TMS Entertainment",Original,15 min per ep,G - All Ages,13327,16545,0,UNKNOWN,348,https://cdn.myanimelist.net/images/anime/11/36...
2508,2735,Mugen Senki Portriss,UNKNOWN,無限戦記ポトリス,UNKNOWN,"Action, Sci-Fi","In a raving world, legendary knights stood up....",TV,52,"Apr 5, 2003 to Mar 27, 2004",...,"Sunrise, Dongwoo A&E",Unknown,25 min per ep,PG - Children,18320,14460,1,UNKNOWN,567,https://cdn.myanimelist.net/images/anime/1627/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24900,55731,Wu Nao Monu,UNKNOWN,无脑魔女,UNKNOWN,"Comedy, Fantasy, Slice of Life",No description available for this anime.,ONA,15,"Jul 4, 2023 to ?",...,UNKNOWN,Web manga,Unknown,PG-13 - Teens 13 or older,UNKNOWN,24723,0,UNKNOWN,0,https://cdn.myanimelist.net/images/anime/1386/...
24901,55732,Bu Xing Si: Yuan Qi,Blader Soul,捕星司·源起,UNKNOWN,"Action, Adventure, Fantasy",No description available for this anime.,ONA,18,"Jul 27, 2023 to ?",...,UNKNOWN,Web novel,Unknown,PG-13 - Teens 13 or older,0,0,0,UNKNOWN,0,https://cdn.myanimelist.net/images/anime/1383/...
24902,55733,Di Yi Xulie,The First Order,第一序列,UNKNOWN,"Action, Adventure, Fantasy, Sci-Fi",No description available for this anime.,ONA,16,"Jul 19, 2023 to ?",...,UNKNOWN,Web novel,Unknown,PG-13 - Teens 13 or older,0,0,0,UNKNOWN,0,https://cdn.myanimelist.net/images/anime/1130/...
24903,55734,Bokura no Saishuu Sensou,UNKNOWN,僕らの最終戦争,UNKNOWN,UNKNOWN,A music video for the song Bokura no Saishuu S...,Music,1,"Apr 23, 2022",...,UNKNOWN,Original,3 min,PG-13 - Teens 13 or older,0,0,0,UNKNOWN,0,https://cdn.myanimelist.net/images/anime/1931/...
24904,55735,Shijuuku Nichi,UNKNOWN,四十九日,UNKNOWN,UNKNOWN,A music video for the song Shijuuku Nichi by S...,Music,1,"Sep 5, 2022",...,UNKNOWN,Original,3 min,PG-13 - Teens 13 or older,0,0,0,UNKNOWN,0,https://cdn.myanimelist.net/images/anime/1902/...

In [6]:
data["Score"] = data["Score"].replace("UNKNOWN", 0)
data["Score"] = data["Score"].astype(float)

In [7]:
data["Score"][1578]

np.float64(0.0)

In [8]:
data.query("Rank=='UNKNOWN'")

,anime_id,Name,English name,Other name,Score,Genres,Synopsis,Type,Episodes,Aired,...,Studios,Source,Duration,Rating,Rank,Popularity,Favorites,Scored By,Members,Image URL
165,188,Gosenzo San'e,Masquerade,御先祖賛江,6.03,"Comedy, Mystery, Supernatural, Hentai",Masquerade is the story surrounding the Hiraga...,OVA,4,"Sep 25, 1998 to Mar 25, 1999",...,AIC,Original,30 min per ep,Rx - Hentai,UNKNOWN,9464,7,978,3025,https://cdn.myanimelist.net/images/anime/13/78...
180,203,Words Worth,UNKNOWN,ワーズ・ワース,6.72,"Adventure, Fantasy, Hentai",The legend has survived for generation. The Wo...,OVA,5,"Aug 25, 1999 to Nov 25, 2000",...,Arms,Visual novel,28 min per ep,Rx - Hentai,UNKNOWN,6424,36,3559,8596,https://cdn.myanimelist.net/images/anime/12/60...
188,211,Pure Mail,UNKNOWN,ピュアメール,6.17,Hentai,"Episode 1:\n""There is no need for relationship...",OVA,2,"Sep 25, 2001 to Dec 21, 2001",...,Datama Film,Visual novel,29 min per ep,Rx - Hentai,UNKNOWN,8824,13,1454,3735,https://cdn.myanimelist.net/images/anime/1518/...
190,213,Pia Carrot e Youkoso!!,Welcome to Pia Carrot,Piaキャロットへようこそ!!,5.94,"Comedy, Hentai",Yusuke Kinoshita is forced by his father to wo...,OVA,3,"Oct 24, 1997 to Apr 24, 1998",...,Triple X,Visual novel,27 min per ep,Rx - Hentai,UNKNOWN,8947,3,1266,3582,https://cdn.myanimelist.net/images/anime/1111/...
191,214,Pia Carrot e Youkoso!! 2,Welcome To Pia Carrot 2,Piaキャロットへようこそ!! 2,6.07,"Comedy, Romance, Hentai",Yusuke (from the first Pia Carrot series) retu...,OVA,3,"Oct 23, 1998 to Apr 23, 1999",...,Triple X,Visual novel,28 min per ep,Rx - Hentai,UNKNOWN,10014,5,912,2472,https://cdn.myanimelist.net/images/anime/1610/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24880,55707,Kokoro,UNKNOWN,心,0.00,UNKNOWN,Music video for the song Kokoro by Shikidrop.,Music,1,"Jul 30, 2020",...,UNKNOWN,Original,4 min,PG-13 - Teens 13 or older,UNKNOWN,24664,0,UNKNOWN,31,https://cdn.myanimelist.net/images/anime/1146/...
24881,55708,Nazukeau Tabiji,UNKNOWN,名付け合う旅路,0.00,UNKNOWN,Music video for the song Nazukeau Tabiji by Sh...,Music,1,"Feb 9, 2022",...,UNKNOWN,Original,4 min,G - All Ages,UNKNOWN,24675,0,UNKNOWN,29,https://cdn.myanimelist.net/images/anime/1564/...
24882,55709,Boku to Roboko Movie,UNKNOWN,僕とロボコ 劇場版,0.00,"Comedy, Sci-Fi",The movie version of Boku to Roboko.,Movie,1,2024,...,UNKNOWN,Manga,Unknown,PG-13 - Teens 13 or older,UNKNOWN,17604,0,UNKNOWN,265,https://cdn.myanimelist.net/images/anime/1277/...
24883,55710,Hana-Doll*: Reinterpretation of Flowering,UNKNOWN,華Doll* -Reinterpretation of Flowering-,0.00,UNKNOWN,"The ""Hana Ningyou Project"" (Flower Doll Projec...",UNKNOWN,0,Not available,...,UNKNOWN,Original,Unknown,UNKNOWN,UNKNOWN,24637,0,UNKNOWN,38,https://cdn.myanimelist.net/images/anime/1941/...
24900,55731,Wu Nao Monu,UNKNOWN,无脑魔女,0.00,"Comedy, Fantasy, Slice of Life",No description available for this anime.,ONA,15,"Jul 4, 2023 to ?",...,UNKNOWN,Web manga,Unknown,PG-13 - Teens 13 or older,UNKNOWN,24723,0,UNKNOWN,0,https://cdn.myanimelist.net/images/anime/1386/...

In [9]:
data["Rank"] = data["Rank"].replace("UNKNOWN", 0)
data["Rank"] = data["Rank"].astype(int)

In [10]:
data.query("`Scored By`=='UNKNOWN'")

,anime_id,Name,English name,Other name,Score,Genres,Synopsis,Type,Episodes,Aired,...,Studios,Source,Duration,Rating,Rank,Popularity,Favorites,Scored By,Members,Image URL
1578,1739,Shibawanko no Wa no Kokoro,UNKNOWN,しばわんこの和のこころ,0.0,UNKNOWN,Based on a japanese children`s book by Yoshie ...,TV,80,"Apr 5, 2006 to Mar 14, 2007",...,Three-d,Unknown,2 min per ep,G - All Ages,19660,13679,1,UNKNOWN,728,https://cdn.myanimelist.net/images/anime/11/70...
1699,1863,Silk Road Shounen Yuuto,UNKNOWN,シルクロード少年 ユート,0.0,"Adventure, Fantasy","When a boy Yuto visits Qinghai in China, he is...",TV,26,"Sep 16, 2006 to Mar 24, 2007",...,OLM,Unknown,20 min per ep,UNKNOWN,19912,13981,0,UNKNOWN,657,https://cdn.myanimelist.net/images/anime/1/186...
2476,2701,Susie-chan to Marvy,Little Susie and Marvy,スージーちゃんとマービー,0.0,Comedy,No description available for this anime.,TV,104,"Apr 5, 1999 to Feb 3, 2000",...,Xebec,Unknown,15 min per ep,UNKNOWN,12706,16212,0,UNKNOWN,374,https://cdn.myanimelist.net/images/anime/10/36...
2483,2708,Wankorobee,UNKNOWN,わんころべえ,0.0,"Comedy, Fantasy",No description available for this anime.,TV,26,"Oct 6, 1996 to Mar 30, 1997",...,"Ajia-do, TMS Entertainment",Original,15 min per ep,G - All Ages,13327,16545,0,UNKNOWN,348,https://cdn.myanimelist.net/images/anime/11/36...
2508,2735,Mugen Senki Portriss,UNKNOWN,無限戦記ポトリス,0.0,"Action, Sci-Fi","In a raving world, legendary knights stood up....",TV,52,"Apr 5, 2003 to Mar 27, 2004",...,"Sunrise, Dongwoo A&E",Unknown,25 min per ep,PG - Children,18320,14460,1,UNKNOWN,567,https://cdn.myanimelist.net/images/anime/1627/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24900,55731,Wu Nao Monu,UNKNOWN,无脑魔女,0.0,"Comedy, Fantasy, Slice of Life",No description available for this anime.,ONA,15,"Jul 4, 2023 to ?",...,UNKNOWN,Web manga,Unknown,PG-13 - Teens 13 or older,0,24723,0,UNKNOWN,0,https://cdn.myanimelist.net/images/anime/1386/...
24901,55732,Bu Xing Si: Yuan Qi,Blader Soul,捕星司·源起,0.0,"Action, Adventure, Fantasy",No description available for this anime.,ONA,18,"Jul 27, 2023 to ?",...,UNKNOWN,Web novel,Unknown,PG-13 - Teens 13 or older,0,0,0,UNKNOWN,0,https://cdn.myanimelist.net/images/anime/1383/...
24902,55733,Di Yi Xulie,The First Order,第一序列,0.0,"Action, Adventure, Fantasy, Sci-Fi",No description available for this anime.,ONA,16,"Jul 19, 2023 to ?",...,UNKNOWN,Web novel,Unknown,PG-13 - Teens 13 or older,0,0,0,UNKNOWN,0,https://cdn.myanimelist.net/images/anime/1130/...
24903,55734,Bokura no Saishuu Sensou,UNKNOWN,僕らの最終戦争,0.0,UNKNOWN,A music video for the song Bokura no Saishuu S...,Music,1,"Apr 23, 2022",...,UNKNOWN,Original,3 min,PG-13 - Teens 13 or older,0,0,0,UNKNOWN,0,https://cdn.myanimelist.net/images/anime/1931/...
24904,55735,Shijuuku Nichi,UNKNOWN,四十九日,0.0,UNKNOWN,A music video for the song Shijuuku Nichi by S...,Music,1,"Sep 5, 2022",...,UNKNOWN,Original,3 min,PG-13 - Teens 13 or older,0,0,0,UNKNOWN,0,https://cdn.myanimelist.net/images/anime/1902/...

In [11]:
data["Scored By"] = data["Scored By"].replace("UNKNOWN", 0)
data["Scored By"] = data["Scored By"].astype(int)

In [12]:
data["Scored By"][1578]

np.int64(0)

In [13]:
data["Aired"] = pd.to_datetime(
    data["Aired"],
    format="%b %d, %Y",
    errors="coerce"
)

In [15]:
data["Aired"]

0              NaT
1       2001-09-01
2              NaT
3              NaT
4              NaT
           ...
24900          NaT
24901          NaT
24902          NaT
24903   2022-04-23
24904   2022-09-05
Name: Aired, Length: 24905, dtype: datetime64[us]