In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("anime-dataset-2023.csv")

This output is exactly what you want to see when doing Exploratory Data Analysis (EDA). By adding that count column, the story your data is telling becomes incredibly clear.

Here are the key analytical insights you can extract from this table, formatted as highly testable concepts for your notes.

1. The "Zero Score" Missing Data Confirmation
Look at the pure Action row at the very top. It has 256 anime, a maximum score of 8.03, and a minimum score of 0.00. The Action, Adventure, Comedy, Fantasy row has 51 anime, a max of 7.65, and a min of 0.00.

Because we see a 0.00 minimum in groups with large sample sizes, it practically guarantees that 0.00 is not a legitimate user rating. It is a placeholder for NaN (Not a Number) or missing data (e.g., an upcoming anime that hasn't aired yet).

2. The "Long Tail" Distribution of Categories
Notice the relationship between the length of the genre name and the count column:

Broad Categories: Simple labels like Action (256 count) or Action, Adventure (57 count) have the highest volume.

Hyper-Specific Categories: The more tags an anime has (e.g., Action, Adventure, Comedy, Drama, Sci-Fi), the lower the count drops, almost exclusively hitting 1, 2, or 3.

In data science, this is known as high cardinality or a "long tail" distribution. Grouping by exact string matches on columns with dozens of comma-separated tags creates hundreds of useless micro-groups.

3. The Singleton Trap Unveiled
Our previous suspicion is completely validated by the count column. Look at the middle section filled with rows that have a count of 1.

For Action, Adventure, Award Winning, Comedy, Mystery, the min is 8.15 and the max is 8.15. Because the count is exactly 1, calculating variance, standard deviation, or mean for this specific group is statistically meaningless.

4. The True Anomalies
Look at Action, Adventure, Comedy, Fantasy, Supernatural. The minimum is 0.00, the maximum is 0.00, and the count is 1. This means there is exactly one show in this highly specific genre combination, and its score data is completely missing.

📚 Data Science Study Notes: Handling Dirty Data
When dealing with dirty datasets containing placeholders like 0.00, you will generally be tested on two primary solutions:

Dropping (Listwise Deletion): Removing any row where the score is 0.00 before running your .groupby(). This is safe if the missing data is a small percentage of the total dataset.

Imputation: Replacing the 0.00 with the median or mean score of that specific genre. This is riskier but preserves your row counts.

Given that these 0.00 placeholders will severely drag down the average scores of your major genre categories, how would you prefer to clean them out of the dataset before we calculate the final means?

In [5]:
scorex = np.array(df['Score'])

In [6]:
scorex

array([8.75, 8.38, 8.22, ..., 0.  , 0.  , 0.  ], shape=(24905,))

In [8]:
mean_score = np.mean(scorex)
print(mean_score)

4.020434450913471

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 24905 entries, 0 to 24904
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   anime_id          24905 non-null  int64
 1   Name              24905 non-null  str
 2   English name      24905 non-null  str
 3   Other name        24905 non-null  str
 4   Score             24905 non-null  float64
 5   Genres            24905 non-null  str
 6   Synopsis          24905 non-null  str
 7   Type              24905 non-null  str
 8   Episodes          24905 non-null  int64
 9   Aired             24905 non-null  str
 10  Premiered         24905 non-null  str
 11  Status            24905 non-null  str
 12  Producers         24905 non-null  str
 13  Licensors         24905 non-null  str
 14  Studios           24905 non-null  str
 15  Source            24905 non-null  str
 16  Rating            24905 non-null  str
 17  Rank              24905 non-null  int64
 18  Popularity        24905 non-null  int64
 19  Favorites         24905 non-null  int64
 20  Scored By         24905 non-null  int64
 21  Members           24905 non-null  int64
 22  Image URL         24905 non-null  str
 23  Duration_Minutes  24242 non-null  float64
dtypes: float64(2), int64(7), str(15)
memory usage: 4.6 MB

In [ ]:
pd.set_option('display.max_rows', None)
df.groupby(["Episodes", "Genres"])["Score"].mean()

Episodes  Genres
0         Action                                                                       0.259048
          Action, Adventure                                                            0.000000
          Action, Adventure, Comedy, Fantasy                                           0.835556
          Action, Adventure, Comedy, Fantasy, Romance                                  0.000000
          Action, Adventure, Drama, Fantasy                                            0.000000
          Action, Adventure, Drama, Fantasy, Mystery                                   0.000000
          Action, Adventure, Drama, Fantasy, Supernatural                              0.000000
          Action, Adventure, Fantasy                                                   0.740667
          Action, Adventure, Fantasy, Romance                                          3.585000
          Action, Adventure, Fantasy, Sci-Fi                                           3.715000
          Action, Adventure, Fantasy, Supernatural                                     0.000000
          Action, Adventure, Sci-Fi                                                    0.000000
          Action, Avant Garde, Comedy, Sci-Fi                                          0.000000
          Action, Comedy                                                               0.000000
          Action, Comedy, Drama                                                        0.000000
          Action, Comedy, Drama, Fantasy, Romance, Ecchi                               0.000000
          Action, Comedy, Drama, Sci-Fi                                                0.000000
          Action, Comedy, Fantasy                                                      0.885000
          Action, Comedy, Horror, Supernatural, Suspense                               0.000000
          Action, Comedy, Romance                                                      0.000000
          Action, Comedy, Supernatural                                                 0.000000
          Action, Comedy, Supernatural, Ecchi                                          0.000000
          Action, Drama                                                                0.000000
          Action, Drama, Fantasy                                                       0.000000
          Action, Drama, Sci-Fi                                                        0.000000
          Action, Drama, Supernatural                                                  0.000000
          Action, Fantasy                                                              1.195429
          Action, Fantasy, Ecchi                                                       0.000000
          Action, Fantasy, Mystery                                                     0.000000
          Action, Fantasy, Romance                                                     1.722500
          Action, Fantasy, Romance, Ecchi                                              0.000000
          Action, Fantasy, Romance, Sci-Fi                                             0.000000
          Action, Fantasy, Sci-Fi                                                      2.470000
          Action, Fantasy, Sci-Fi, Sports                                              0.000000
          Action, Fantasy, Supernatural                                                0.000000
          Action, Fantasy, Suspense                                                    0.000000
          Action, Mystery, Sci-Fi, Suspense                                            0.000000
          Action, Mystery, Supernatural                                                0.000000
          Action, Mystery, Supernatural, Suspense                                      0.000000
          Action, Romance                                                              0.000000
          Action, Romance, Sci-Fi                                                      0.000000
          Action, Sci-Fi                                                               0.000000
          Action, Sci-Fi, Supernatural                                                 0.000000
          Action, Slice of Life                                                        0.000000
          Action, Sports                                                               0.000000
          Action, Supernatural                                                         0.000000
          Adventure                                                                    0.000000
          Adventure, Award Winning, Comedy, Fantasy                                    6.320000
          Adventure, Comedy                                                            0.000000
          Adventure, Comedy, Fantasy                                                   0.000000
          Adventure, Comedy, Fantasy, Romance                                          0.000000
          Adventure, Comedy, Mystery                                                   8.170000
          Adventure, Comedy, Sci-Fi                                                    0.000000
          Adventure, Comedy, Sports                                                    0.000000
          Adventure, Comedy, Supernatural                                              0.000000
          Adventure, Drama, Fantasy                                                    0.000000
          Adventure, Drama, Fantasy, Mystery, Sci-Fi, Suspense                         0.000000
          Adventure, Drama, Fantasy, Romance                                           0.000000
          Adventure, Drama, Supernatural                                               0.000000
          Adventure, Fantasy                                                           0.000000
          Adventure, Fantasy, Romance                                                  0.000000
          Adventure, Fantasy, Slice of Life                                            0.000000
          Adventure, Romance, Sci-Fi                                                   0.000000
          Adventure, Slice of Life                                                     0.000000
          Avant Garde, Horror, Supernatural                                            0.000000
          Boys Love, Comedy                                                            0.000000
          Boys Love, Comedy, Drama, Fantasy                                            0.000000
          Boys Love, Drama, Fantasy, Supernatural                                      0.000000
          Comedy                                                                       0.992836
          Comedy, Drama, Fantasy                                                       6.120000
          Comedy, Drama, Romance                                                       0.000000
          Comedy, Ecchi                                                                1.942500
          Comedy, Fantasy                                                              0.563636
          Comedy, Fantasy, Girls Love, Romance                                         0.000000
          Comedy, Fantasy, Gourmet                                                     0.000000
          Comedy, Fantasy, Romance                                                     0.000000
          Comedy, Fantasy, Supernatural                                                0.000000
          Comedy, Girls Love                                                           0.000000
          Comedy, Girls Love, Supernatural                                             0.000000
          Comedy, Gourmet                                                              3.515000
          Comedy, Mystery                                                              0.000000
          Comedy, Mystery, Romance                                                     0.000000
          Comedy, Romance                                                              0.000000
          Comedy, Romance, Ecchi                                                       0.000000
          Comedy, Sci-Fi                                                               2.546667
          Comedy, Slice of Life                                                        1.231875
          Comedy, Sports                                                               0.000000
          Comedy, Supernatural                                                         0.000000
          Drama                                                                        1.045000
          Drama, Fantasy                                                               0.000000
          Drama, Fantasy, Ecchi                                                        0.000000
          Drama, Fantasy, Romance                                                      0.000000
          Drama, Fantasy, Romance, Sci-Fi, Supernatural, Suspense                      0.000000
          Drama, Fantasy, Supernatural                                                 0.000000
          Drama, Fantasy, Suspense                                                     0.000000
          Drama, Gourmet                                                               0.000000
          Drama, Mystery                                                               0.000000
          Drama, Romance                                                               0.000000
          Drama, Sci-Fi                                                                0.000000
          Drama, Sci-Fi, Suspense                                                      0.000000
          Drama, Slice of Life                                                         0.000000
          Drama, Sports                                                                0.000000
          Drama, Supernatural                                                          0.000000
          Drama, Suspense                                                              0.000000
          Ecchi                                                                        0.000000
          Fantasy                                                                      1.244074
          Fantasy, Gourmet, Slice of Life                                              0.000000
          Fantasy, Hentai                                                              5.733333
          Fantasy, Romance                                                             0.000000
          Fantasy, Romance, Supernatural                                               0.000000
          Fantasy, Slice of Life                                                       0.000000
          Fantasy, Supernatural                                                        0.000000
          Fantasy, Suspense, Ecchi                                                     0.000000
          Girls Love                                                                   0.000000
          Hentai                                                                       5.391316
          Horror, Romance, Supernatural, Ecchi                                         0.000000
          Horror, Supernatural                                                         0.000000
          Horror, Supernatural, Suspense                                               0.000000
          Mystery                                                                      5.890000
          Mystery, Sci-Fi                                                              0.000000
          Mystery, Supernatural                                                        0.000000
          Romance                                                                      0.000000
          Romance, Slice of Life                                                       0.000000
          Sci-Fi                                                                       1.412500
          Sci-Fi, Suspense                                                             5.720000
          Slice of Life                                                                0.469333
          Slice of Life, Supernatural                                                  0.000000
          Sports                                                                       0.000000
          Supernatural                                                                 0.000000
          Supernatural, Hentai                                                         3.525000
          Suspense                                                                     7.900000
          UNKNOWN                                                                      0.220000
1         Action                                                                       4.554922
          Action, Adventure                                                            3.611754
          Action, Adventure, Avant Garde, Mystery, Supernatural                        5.750000
          Action, Adventure, Award Winning, Comedy, Drama, Fantasy                     7.750000
          Action, Adventure, Award Winning, Comedy, Drama, Romance                     7.950000
          Action, Adventure, Award Winning, Comedy, Mystery                            8.150000
          Action, Adventure, Award Winning, Drama, Fantasy, Romance                    8.250000
          Action, Adventure, Award Winning, Fantasy                                    8.670000
          Action, Adventure, Award Winning, Supernatural                               7.950000
          Action, Adventure, Comedy                                                    5.401071
          Action, Adventure, Comedy, Drama                                             7.201250
          Action, Adventure, Comedy, Drama, Fantasy                                    6.152500
          Action, Adventure, Comedy, Drama, Romance, Sci-Fi                            7.044286
          Action, Adventure, Comedy, Drama, Sci-Fi                                     6.823333
          Action, Adventure, Comedy, Ecchi                                             4.600000
          Action, Adventure, Comedy, Fantasy                                           5.987647
          Action, Adventure, Comedy, Fantasy, Sci-Fi                                   6.162353
          Action, Adventure, Comedy, Fantasy, Sci-Fi, Supernatural                     6.530000
          Action, Adventure, Comedy, Fantasy, Slice of Life                            6.500000
          Action, Adventure, Comedy, Fantasy, Sports                                   5.700000
          Action, Adventure, Comedy, Fantasy, Supernatural                             0.000000
          Action, Adventure, Comedy, Gourmet                                           6.743333
          Action, Adventure, Comedy, Mystery                                           6.958750
          Action, Adventure, Comedy, Romance                                           7.170000
          Action, Adventure, Comedy, Romance, Sci-Fi, Ecchi                            6.120000
          Action, Adventure, Comedy, Romance, Supernatural, Ecchi                      6.370000
          Action, Adventure, Comedy, Sci-Fi                                            6.130833
          Action, Adventure, Comedy, Sci-Fi, Ecchi                                     6.820000
          Action, Adventure, Comedy, Sci-Fi, Sports                                    6.610000
          Action, Adventure, Comedy, Sci-Fi, Suspense                                  7.000000
          Action, Adventure, Comedy, Supernatural                                      6.690000
          Action, Adventure, Drama                                                     6.224167
          Action, Adventure, Drama, Fantasy                                            6.045455
          Action, Adventure, Drama, Fantasy, Horror                                    7.447500
          Action, Adventure, Drama, Fantasy, Horror, Supernatural                      5.800000
          Action, Adventure, Drama, Fantasy, Romance                                   7.420000
          Action, Adventure, Drama, Fantasy, Sci-Fi                                    7.300000
          Action, Adventure, Drama, Fantasy, Supernatural                              6.560000
          Action, Adventure, Drama, Horror                                             6.440000
          Action, Adventure, Drama, Mystery, Romance, Sci-Fi                           6.145000
          Action, Adventure, Drama, Romance                                            6.486667
          Action, Adventure, Drama, Romance, Sci-Fi                                    5.490000
          Action, Adventure, Drama, Romance, Supernatural                              7.050000
          Action, Adventure, Drama, Sci-Fi                                             5.672941
          Action, Adventure, Drama, Sci-Fi, Supernatural                               5.150000
          Action, Adventure, Fantasy                                                   5.957432
          Action, Adventure, Fantasy, Ecchi                                            7.180000
          Action, Adventure, Fantasy, Horror, Supernatural                             6.330000
          Action, Adventure, Fantasy, Mystery, Sci-Fi                                  7.060000
          Action, Adventure, Fantasy, Romance                                          5.825455
          Action, Adventure, Fantasy, Romance, Supernatural                            5.640000
          Action, Adventure, Fantasy, Sci-Fi                                           4.049286
          Action, Adventure, Fantasy, Supernatural                                     4.048333
          Action, Adventure, Horror                                                    6.560000
          Action, Adventure, Horror, Sci-Fi, Hentai                                    5.210000
          Action, Adventure, Horror, Sci-Fi, Supernatural                              8.160000
          Action, Adventure, Mystery                                                   3.020000
          Action, Adventure, Mystery, Sci-Fi                                           6.200000
          Action, Adventure, Mystery, Supernatural                                     7.270000
          Action, Adventure, Romance                                                   6.075000
          Action, Adventure, Romance, Sci-Fi                                           6.940000
          Action, Adventure, Sci-Fi                                                    4.509315
          Action, Adventure, Supernatural                                              5.865000
          Action, Avant Garde                                                          5.040000
          Action, Avant Garde, Comedy, Sci-Fi                                          6.435000
          Action, Avant Garde, Comedy, Supernatural, Ecchi                             6.380000
          Action, Avant Garde, Drama, Horror                                           5.600000
          Action, Avant Garde, Drama, Sci-Fi                                           6.310000
          Action, Avant Garde, Horror, Sci-Fi                                          5.940000
          Action, Avant Garde, Sci-Fi                                                  0.000000
          Action, Award Winning                                                        8.180000
          Action, Award Winning, Comedy                                                5.700000
          Action, Award Winning, Drama                                                 1.883333
          Action, Award Winning, Drama, Mystery                                        7.850000
          Action, Award Winning, Drama, Sci-Fi                                         7.512000
          Action, Award Winning, Drama, Sci-Fi, Suspense                               8.610000

In [18]:
pd.set_option('display.max_rows', None)
df.groupby(["Episodes", "Genres"])["Score"].max()

Episodes  Genres
0         Action                                                                       5.44
          Action, Adventure                                                            0.00
          Action, Adventure, Comedy, Fantasy                                           7.52
          Action, Adventure, Comedy, Fantasy, Romance                                  0.00
          Action, Adventure, Drama, Fantasy                                            0.00
          Action, Adventure, Drama, Fantasy, Mystery                                   0.00
          Action, Adventure, Drama, Fantasy, Supernatural                              0.00
          Action, Adventure, Fantasy                                                   8.69
          Action, Adventure, Fantasy, Romance                                          7.31
          Action, Adventure, Fantasy, Sci-Fi                                           7.43
          Action, Adventure, Fantasy, Supernatural                                     0.00
          Action, Adventure, Sci-Fi                                                    0.00
          Action, Avant Garde, Comedy, Sci-Fi                                          0.00
          Action, Comedy                                                               0.00
          Action, Comedy, Drama                                                        0.00
          Action, Comedy, Drama, Fantasy, Romance, Ecchi                               0.00
          Action, Comedy, Drama, Sci-Fi                                                0.00
          Action, Comedy, Fantasy                                                      5.31
          Action, Comedy, Horror, Supernatural, Suspense                               0.00
          Action, Comedy, Romance                                                      0.00
          Action, Comedy, Supernatural                                                 0.00
          Action, Comedy, Supernatural, Ecchi                                          0.00
          Action, Drama                                                                0.00
          Action, Drama, Fantasy                                                       0.00
          Action, Drama, Sci-Fi                                                        0.00
          Action, Drama, Supernatural                                                  0.00
          Action, Fantasy                                                              7.69
          Action, Fantasy, Ecchi                                                       0.00
          Action, Fantasy, Mystery                                                     0.00
          Action, Fantasy, Romance                                                     6.89
          Action, Fantasy, Romance, Ecchi                                              0.00
          Action, Fantasy, Romance, Sci-Fi                                             0.00
          Action, Fantasy, Sci-Fi                                                      7.41
          Action, Fantasy, Sci-Fi, Sports                                              0.00
          Action, Fantasy, Supernatural                                                0.00
          Action, Fantasy, Suspense                                                    0.00
          Action, Mystery, Sci-Fi, Suspense                                            0.00
          Action, Mystery, Supernatural                                                0.00
          Action, Mystery, Supernatural, Suspense                                      0.00
          Action, Romance                                                              0.00
          Action, Romance, Sci-Fi                                                      0.00
          Action, Sci-Fi                                                               0.00
          Action, Sci-Fi, Supernatural                                                 0.00
          Action, Slice of Life                                                        0.00
          Action, Sports                                                               0.00
          Action, Supernatural                                                         0.00
          Adventure                                                                    0.00
          Adventure, Award Winning, Comedy, Fantasy                                    6.32
          Adventure, Comedy                                                            0.00
          Adventure, Comedy, Fantasy                                                   0.00
          Adventure, Comedy, Fantasy, Romance                                          0.00
          Adventure, Comedy, Mystery                                                   8.17
          Adventure, Comedy, Sci-Fi                                                    0.00
          Adventure, Comedy, Sports                                                    0.00
          Adventure, Comedy, Supernatural                                              0.00
          Adventure, Drama, Fantasy                                                    0.00
          Adventure, Drama, Fantasy, Mystery, Sci-Fi, Suspense                         0.00
          Adventure, Drama, Fantasy, Romance                                           0.00
          Adventure, Drama, Supernatural                                               0.00
          Adventure, Fantasy                                                           0.00
          Adventure, Fantasy, Romance                                                  0.00
          Adventure, Fantasy, Slice of Life                                            0.00
          Adventure, Romance, Sci-Fi                                                   0.00
          Adventure, Slice of Life                                                     0.00
          Avant Garde, Horror, Supernatural                                            0.00
          Boys Love, Comedy                                                            0.00
          Boys Love, Comedy, Drama, Fantasy                                            0.00
          Boys Love, Drama, Fantasy, Supernatural                                      0.00
          Comedy                                                                       8.24
          Comedy, Drama, Fantasy                                                       6.12
          Comedy, Drama, Romance                                                       0.00
          Comedy, Ecchi                                                                7.77
          Comedy, Fantasy                                                              6.53
          Comedy, Fantasy, Girls Love, Romance                                         0.00
          Comedy, Fantasy, Gourmet                                                     0.00
          Comedy, Fantasy, Romance                                                     0.00
          Comedy, Fantasy, Supernatural                                                0.00
          Comedy, Girls Love                                                           0.00
          Comedy, Girls Love, Supernatural                                             0.00
          Comedy, Gourmet                                                              7.03
          Comedy, Mystery                                                              0.00
          Comedy, Mystery, Romance                                                     0.00
          Comedy, Romance                                                              0.00
          Comedy, Romance, Ecchi                                                       0.00
          Comedy, Sci-Fi                                                               7.64
          Comedy, Slice of Life                                                        7.27
          Comedy, Sports                                                               0.00
          Comedy, Supernatural                                                         0.00
          Drama                                                                        6.27
          Drama, Fantasy                                                               0.00
          Drama, Fantasy, Ecchi                                                        0.00
          Drama, Fantasy, Romance                                                      0.00
          Drama, Fantasy, Romance, Sci-Fi, Supernatural, Suspense                      0.00
          Drama, Fantasy, Supernatural                                                 0.00
          Drama, Fantasy, Suspense                                                     0.00
          Drama, Gourmet                                                               0.00
          Drama, Mystery                                                               0.00
          Drama, Romance                                                               0.00
          Drama, Sci-Fi                                                                0.00
          Drama, Sci-Fi, Suspense                                                      0.00
          Drama, Slice of Life                                                         0.00
          Drama, Sports                                                                0.00
          Drama, Supernatural                                                          0.00
          Drama, Suspense                                                              0.00
          Ecchi                                                                        0.00
          Fantasy                                                                      7.25
          Fantasy, Gourmet, Slice of Life                                              0.00
          Fantasy, Hentai                                                              5.92
          Fantasy, Romance                                                             0.00
          Fantasy, Romance, Supernatural                                               0.00
          Fantasy, Slice of Life                                                       0.00
          Fantasy, Supernatural                                                        0.00
          Fantasy, Suspense, Ecchi                                                     0.00
          Girls Love                                                                   0.00
          Hentai                                                                       7.75
          Horror, Romance, Supernatural, Ecchi                                         0.00
          Horror, Supernatural                                                         0.00
          Horror, Supernatural, Suspense                                               0.00
          Mystery                                                                      5.89
          Mystery, Sci-Fi                                                              0.00
          Mystery, Supernatural                                                        0.00
          Romance                                                                      0.00
          Romance, Slice of Life                                                       0.00
          Sci-Fi                                                                       5.65
          Sci-Fi, Suspense                                                             5.72
          Slice of Life                                                                7.38
          Slice of Life, Supernatural                                                  0.00
          Sports                                                                       0.00
          Supernatural                                                                 0.00
          Supernatural, Hentai                                                         7.05
          Suspense                                                                     7.90
          UNKNOWN                                                                      5.92
1         Action                                                                       8.03
          Action, Adventure                                                            8.26
          Action, Adventure, Avant Garde, Mystery, Supernatural                        5.75
          Action, Adventure, Award Winning, Comedy, Drama, Fantasy                     7.86
          Action, Adventure, Award Winning, Comedy, Drama, Romance                     7.95
          Action, Adventure, Award Winning, Comedy, Mystery                            8.15
          Action, Adventure, Award Winning, Drama, Fantasy, Romance                    8.25
          Action, Adventure, Award Winning, Fantasy                                    8.67
          Action, Adventure, Award Winning, Supernatural                               7.95
          Action, Adventure, Comedy                                                    7.33
          Action, Adventure, Comedy, Drama                                             8.17
          Action, Adventure, Comedy, Drama, Fantasy                                    7.50
          Action, Adventure, Comedy, Drama, Romance, Sci-Fi                            7.84
          Action, Adventure, Comedy, Drama, Sci-Fi                                     7.24
          Action, Adventure, Comedy, Ecchi                                             4.60
          Action, Adventure, Comedy, Fantasy                                           7.65
          Action, Adventure, Comedy, Fantasy, Sci-Fi                                   7.58
          Action, Adventure, Comedy, Fantasy, Sci-Fi, Supernatural                     6.53
          Action, Adventure, Comedy, Fantasy, Slice of Life                            6.50
          Action, Adventure, Comedy, Fantasy, Sports                                   5.70
          Action, Adventure, Comedy, Fantasy, Supernatural                             0.00
          Action, Adventure, Comedy, Gourmet                                           6.96
          Action, Adventure, Comedy, Mystery                                           7.82
          Action, Adventure, Comedy, Romance                                           7.17
          Action, Adventure, Comedy, Romance, Sci-Fi, Ecchi                            6.12
          Action, Adventure, Comedy, Romance, Supernatural, Ecchi                      6.37
          Action, Adventure, Comedy, Sci-Fi                                            7.35
          Action, Adventure, Comedy, Sci-Fi, Ecchi                                     6.87
          Action, Adventure, Comedy, Sci-Fi, Sports                                    6.61
          Action, Adventure, Comedy, Sci-Fi, Suspense                                  7.00
          Action, Adventure, Comedy, Supernatural                                      7.35
          Action, Adventure, Drama                                                     7.86
          Action, Adventure, Drama, Fantasy                                            7.74
          Action, Adventure, Drama, Fantasy, Horror                                    8.20
          Action, Adventure, Drama, Fantasy, Horror, Supernatural                      5.80
          Action, Adventure, Drama, Fantasy, Romance                                   7.42
          Action, Adventure, Drama, Fantasy, Sci-Fi                                    7.30
          Action, Adventure, Drama, Fantasy, Supernatural                              6.56
          Action, Adventure, Drama, Horror                                             6.44
          Action, Adventure, Drama, Mystery, Romance, Sci-Fi                           7.03
          Action, Adventure, Drama, Romance                                            6.56
          Action, Adventure, Drama, Romance, Sci-Fi                                    5.49
          Action, Adventure, Drama, Romance, Supernatural                              7.05
          Action, Adventure, Drama, Sci-Fi                                             7.74
          Action, Adventure, Drama, Sci-Fi, Supernatural                               5.15
          Action, Adventure, Fantasy                                                   8.22
          Action, Adventure, Fantasy, Ecchi                                            7.18
          Action, Adventure, Fantasy, Horror, Supernatural                             6.33
          Action, Adventure, Fantasy, Mystery, Sci-Fi                                  7.06
          Action, Adventure, Fantasy, Romance                                          7.80
          Action, Adventure, Fantasy, Romance, Supernatural                            5.64
          Action, Adventure, Fantasy, Sci-Fi                                           7.20
          Action, Adventure, Fantasy, Supernatural                                     6.16
          Action, Adventure, Horror                                                    7.71
          Action, Adventure, Horror, Sci-Fi, Hentai                                    5.21
          Action, Adventure, Horror, Sci-Fi, Supernatural                              8.16
          Action, Adventure, Mystery                                                   6.04
          Action, Adventure, Mystery, Sci-Fi                                           6.20
          Action, Adventure, Mystery, Supernatural                                     7.27
          Action, Adventure, Romance                                                   7.56
          Action, Adventure, Romance, Sci-Fi                                           7.70
          Action, Adventure, Sci-Fi                                                    7.92
          Action, Adventure, Supernatural                                              7.24
          Action, Avant Garde                                                          5.04
          Action, Avant Garde, Comedy, Sci-Fi                                          6.51
          Action, Avant Garde, Comedy, Supernatural, Ecchi                             6.38
          Action, Avant Garde, Drama, Horror                                           5.60
          Action, Avant Garde, Drama, Sci-Fi                                           6.31
          Action, Avant Garde, Horror, Sci-Fi                                          5.94
          Action, Avant Garde, Sci-Fi                                                  0.00
          Action, Award Winning                                                        8.18
          Action, Award Winning, Comedy                                                6.16
          Action, Award Winning, Drama                                                 5.65
          Action, Award Winning, Drama, Mystery                                        7.85
          Action, Award Winning, Drama, Sci-Fi                                         8.00
          Action, Award Winning, Drama, Sci-Fi, Suspense                               8.61
          Action, Award Winning, Mystery, Sci-Fi                                       7.43
          Action, Award Winning, Mystery, Sci-Fi, Suspense                             8.27
          Action, Award Winning, Romance, Sci-Fi                                       7.94
          Action, Award Winning, Sci-Fi                                                0.00
          Action, Award Winning, Supernatural                                          6.49
          Action, Boys Love, Comedy, Fantasy, Mystery, Supernatural                    6.78
          Action, Boys Love, Drama, Erotica                                            6.86
          Action, Boys Love, Drama, Supernatural                                       6.09
          Action, Boys Love, Fantasy, Supernatural                                     6.76

In [20]:
pd.set_option('display.max_rows', None)
df.groupby(["Episodes", "Genres"])["Score"].agg(['min', 'max', 'count'])

                                                              min   max  count
Episodes Genres
0        Action                                              0.00  5.44     21
         Action, Adventure                                   0.00  0.00      1
         Action, Adventure, Comedy, Fantasy                  0.00  7.52      9
         Action, Adventure, Comedy, Fantasy, Romance         0.00  0.00      1
         Action, Adventure, Drama, Fantasy                   0.00  0.00      1
         Action, Adventure, Drama, Fantasy, Mystery          0.00  0.00      1
         Action, Adventure, Drama, Fantasy, Supernatural     0.00  0.00      1
         Action, Adventure, Fantasy                          0.00  8.69     30
         Action, Adventure, Fantasy, Romance                 0.00  7.31      4
         Action, Adventure, Fantasy, Sci-Fi                  0.00  7.43      2
         Action, Adventure, Fantasy, Supernatural            0.00  0.00      1
         Action, Adventure, Sci-Fi                           0.00  0.00      1
         Action, Avant Garde, Comedy, Sci-Fi                 0.00  0.00      2
         Action, Comedy                                      0.00  0.00      4
         Action, Comedy, Drama                               0.00  0.00      1
         Action, Comedy, Drama, Fantasy, Romance, Ecchi      0.00  0.00      1
         Action, Comedy, Drama, Sci-Fi                       0.00  0.00      1
         Action, Comedy, Fantasy                             0.00  5.31      6
         Action, Comedy, Horror, Supernatural, Suspense      0.00  0.00      1
         Action, Comedy, Romance                             0.00  0.00      1
         Action, Comedy, Supernatural                        0.00  0.00      1
         Action, Comedy, Supernatural, Ecchi                 0.00  0.00      1
         Action, Drama                                       0.00  0.00      2
         Action, Drama, Fantasy                              0.00  0.00      1
         Action, Drama, Sci-Fi                               0.00  0.00      3
         Action, Drama, Supernatural                         0.00  0.00      1
         Action, Fantasy                                     0.00  7.69     35
         Action, Fantasy, Ecchi                              0.00  0.00      2
         Action, Fantasy, Mystery                            0.00  0.00      1
         Action, Fantasy, Romance                            0.00  6.89      4
         Action, Fantasy, Romance, Ecchi                     0.00  0.00      1
         Action, Fantasy, Romance, Sci-Fi                    0.00  0.00      1
         Action, Fantasy, Sci-Fi                             0.00  7.41      3
         Action, Fantasy, Sci-Fi, Sports                     0.00  0.00      1
         Action, Fantasy, Supernatural                       0.00  0.00      2
         Action, Fantasy, Suspense                           0.00  0.00      1
         Action, Mystery, Sci-Fi, Suspense                   0.00  0.00      1
         Action, Mystery, Supernatural                       0.00  0.00      1
         Action, Mystery, Supernatural, Suspense             0.00  0.00      1
         Action, Romance                                     0.00  0.00      1
         Action, Romance, Sci-Fi                             0.00  0.00      2
         Action, Sci-Fi                                      0.00  0.00     15
         Action, Sci-Fi, Supernatural                        0.00  0.00      1
         Action, Slice of Life                               0.00  0.00      2
         Action, Sports                                      0.00  0.00      1
         Action, Supernatural                                0.00  0.00      3
         Adventure                                           0.00  0.00      6
         Adventure, Award Winning, Comedy, Fantasy           6.32  6.32      1
         Adventure, Comedy                                   0.00  0.00      3
         Adventure, Comedy, Fantasy                          0.00  0.00      6
         Adventure, Comedy, Fantasy, Romance                 0.00  0.00      1
         Adventure, Comedy, Mystery                          8.17  8.17      1
         Adventure, Comedy, Sci-Fi                           0.00  0.00      1
         Adventure, Comedy, Sports                           0.00  0.00      1
         Adventure, Comedy, Supernatural                     0.00  0.00      1
         Adventure, Drama, Fantasy                           0.00  0.00      1
         Adventure, Drama, Fantasy, Mystery, Sci-Fi, Sus...  0.00  0.00      1
         Adventure, Drama, Fantasy, Romance                  0.00  0.00      1
         Adventure, Drama, Supernatural                      0.00  0.00      1
         Adventure, Fantasy                                  0.00  0.00      8
         Adventure, Fantasy, Romance                         0.00  0.00      3
         Adventure, Fantasy, Slice of Life                   0.00  0.00      1
         Adventure, Romance, Sci-Fi                          0.00  0.00      1
         Adventure, Slice of Life                            0.00  0.00      1
         Avant Garde, Horror, Supernatural                   0.00  0.00      1
         Boys Love, Comedy                                   0.00  0.00      1
         Boys Love, Comedy, Drama, Fantasy                   0.00  0.00      1
         Boys Love, Drama, Fantasy, Supernatural             0.00  0.00      1
         Comedy                                              0.00  8.24     67
         Comedy, Drama, Fantasy                              6.12  6.12      1
         Comedy, Drama, Romance                              0.00  0.00      1
         Comedy, Ecchi                                       0.00  7.77      4
         Comedy, Fantasy                                     0.00  6.53     22
         Comedy, Fantasy, Girls Love, Romance                0.00  0.00      1
         Comedy, Fantasy, Gourmet                            0.00  0.00      1
         Comedy, Fantasy, Romance                            0.00  0.00      7
         Comedy, Fantasy, Supernatural                       0.00  0.00      1
         Comedy, Girls Love                                  0.00  0.00      2
         Comedy, Girls Love, Supernatural                    0.00  0.00      1
         Comedy, Gourmet                                     0.00  7.03      2
         Comedy, Mystery                                     0.00  0.00      2
         Comedy, Mystery, Romance                            0.00  0.00      1
         Comedy, Romance                                     0.00  0.00     14
         Comedy, Romance, Ecchi                              0.00  0.00      1
         Comedy, Sci-Fi                                      0.00  7.64      3
         Comedy, Slice of Life                               0.00  7.27     16
         Comedy, Sports                                      0.00  0.00      1
         Comedy, Supernatural                                0.00  0.00      9
         Drama                                               0.00  6.27      6
         Drama, Fantasy                                      0.00  0.00      2
         Drama, Fantasy, Ecchi                               0.00  0.00      1
         Drama, Fantasy, Romance                             0.00  0.00      1
         Drama, Fantasy, Romance, Sci-Fi, Supernatural, ...  0.00  0.00      1
         Drama, Fantasy, Supernatural                        0.00  0.00      1
         Drama, Fantasy, Suspense                            0.00  0.00      1
         Drama, Gourmet                                      0.00  0.00      1
         Drama, Mystery                                      0.00  0.00      2
         Drama, Romance                                      0.00  0.00      1
         Drama, Sci-Fi                                       0.00  0.00      1
         Drama, Sci-Fi, Suspense                             0.00  0.00      1
         Drama, Slice of Life                                0.00  0.00      1
         Drama, Sports                                       0.00  0.00      3
         Drama, Supernatural                                 0.00  0.00      2
         Drama, Suspense                                     0.00  0.00      1
         Ecchi                                               0.00  0.00      1
         Fantasy                                             0.00  7.25     27
         Fantasy, Gourmet, Slice of Life                     0.00  0.00      1
         Fantasy, Hentai                                     5.56  5.92      3
         Fantasy, Romance                                    0.00  0.00      6
         Fantasy, Romance, Supernatural                      0.00  0.00      1
         Fantasy, Slice of Life                              0.00  0.00      2
         Fantasy, Supernatural                               0.00  0.00      2
         Fantasy, Suspense, Ecchi                            0.00  0.00      1
         Girls Love                                          0.00  0.00      1
         Hentai                                              0.00  7.75     38
         Horror, Romance, Supernatural, Ecchi                0.00  0.00      1
         Horror, Supernatural                                0.00  0.00      1
         Horror, Supernatural, Suspense                      0.00  0.00      1
         Mystery                                             5.89  5.89      1
         Mystery, Sci-Fi                                     0.00  0.00      1
         Mystery, Supernatural                               0.00  0.00      1
         Romance                                             0.00  0.00      9
         Romance, Slice of Life                              0.00  0.00      1
         Sci-Fi                                              0.00  5.65      4
         Sci-Fi, Suspense                                    5.72  5.72      1
         Slice of Life                                       0.00  7.38     30
         Slice of Life, Supernatural                         0.00  0.00      1
         Sports                                              0.00  0.00     12
         Supernatural                                        0.00  0.00      4
         Supernatural, Hentai                                0.00  7.05      2
         Suspense                                            7.90  7.90      1
         UNKNOWN                                             0.00  5.92     53
1        Action                                              0.00  8.03    256
         Action, Adventure                                   0.00  8.26     57
         Action, Adventure, Avant Garde, Mystery, Supern...  5.75  5.75      1
         Action, Adventure, Award Winning, Comedy, Drama...  7.64  7.86      2
         Action, Adventure, Award Winning, Comedy, Drama...  7.95  7.95      1
         Action, Adventure, Award Winning, Comedy, Mystery   8.15  8.15      1
         Action, Adventure, Award Winning, Drama, Fantas...  8.25  8.25      1
         Action, Adventure, Award Winning, Fantasy           8.67  8.67      1
         Action, Adventure, Award Winning, Supernatural      7.95  7.95      1
         Action, Adventure, Comedy                           0.00  7.33     28
         Action, Adventure, Comedy, Drama                    5.29  8.17      8
         Action, Adventure, Comedy, Drama, Fantasy           0.00  7.50      8
         Action, Adventure, Comedy, Drama, Romance, Sci-Fi   6.61  7.84      7
         Action, Adventure, Comedy, Drama, Sci-Fi            6.34  7.24      3
         Action, Adventure, Comedy, Ecchi                    4.60  4.60      1
         Action, Adventure, Comedy, Fantasy                  0.00  7.65     51
         Action, Adventure, Comedy, Fantasy, Sci-Fi          0.00  7.58     17
         Action, Adventure, Comedy, Fantasy, Sci-Fi, Sup...  6.53  6.53      1
         Action, Adventure, Comedy, Fantasy, Slice of Life   6.50  6.50      1
         Action, Adventure, Comedy, Fantasy, Sports          5.70  5.70      1
         Action, Adventure, Comedy, Fantasy, Supernatural    0.00  0.00      1
         Action, Adventure, Comedy, Gourmet                  6.58  6.96      3
         Action, Adventure, Comedy, Mystery                  5.84  7.82     32
         Action, Adventure, Comedy, Romance                  7.17  7.17      1
         Action, Adventure, Comedy, Romance, Sci-Fi, Ecchi   6.12  6.12      1
         Action, Adventure, Comedy, Romance, Supernatura...  6.37  6.37      1
         Action, Adventure, Comedy, Sci-Fi                   0.00  7.35     12
         Action, Adventure, Comedy, Sci-Fi, Ecchi            6.77  6.87      2
         Action, Adventure, Comedy, Sci-Fi, Sports           6.61  6.61      1
         Action, Adventure, Comedy, Sci-Fi, Suspense         7.00  7.00      1
         Action, Adventure, Comedy, Supernatural             5.44  7.35      4
         Action, Adventure, Drama                            0.00  7.86     12
         Action, Adventure, Drama, Fantasy                   0.00  7.74     11
         Action, Adventure, Drama, Fantasy, Horror           6.02  8.20      4
         Action, Adventure, Drama, Fantasy, Horror, Supe...  5.80  5.80      1
         Action, Adventure, Drama, Fantasy, Romance          7.42  7.42      1
         Action, Adventure, Drama, Fantasy, Sci-Fi           7.30  7.30      1
         Action, Adventure, Drama, Fantasy, Supernatural     6.56  6.56      1
         Action, Adventure, Drama, Horror                    6.44  6.44      1
         Action, Adventure, Drama, Mystery, Romance, Sci-Fi  5.26  7.03      2
         Action, Adventure, Drama, Romance                   6.38  6.56      3
         Action, Adventure, Drama, Romance, Sci-Fi           5.49  5.49      1
         Action, Adventure, Drama, Romance, Supernatural     7.05  7.05      1
         Action, Adventure, Drama, Sci-Fi                    0.00  7.74     17
         Action, Adventure, Drama, Sci-Fi, Supernatural      5.15  5.15      1
         Action, Adventure, Fantasy                          0.00  8.22    148
         Action, Adventure, Fantasy, Ecchi                   7.18  7.18      1
         Action, Adventure, Fantasy, Horror, Supernatural    6.33  6.33      1
         Action, Adventure, Fantasy, Mystery, Sci-Fi         7.06  7.06      1
         Action, Adventure, Fantasy, Romance                 0.00  7.80     11
         Action, Adventure, Fantasy, Romance, Supernatural   5.64  5.64      1
         Action, Adventure, Fantasy, Sci-Fi                  0.00  7.20     14
         Action, Adventure, Fantasy, Supernatural            0.00  6.16      6
         Action, Adventure, Horror                           5.41  7.71      2
         Action, Adventure, Horror, Sci-Fi, Hentai           5.21  5.21      1
         Action, Adventure, Horror, Sci-Fi, Supernatural     8.16  8.16      1
         Action, Adventure, Mystery                          0.00  6.04      2
         Action, Adventure, Mystery, Sci-Fi                  6.20  6.20      1
         Action, Adventure, Mystery, Supernatural            7.27  7.27      1
         Action, Adventure, Romance                          4.59  7.56      2
         Action, Adventure, Romance, Sci-Fi                  6.07  7.70      3
         Action, Adventure, Sci-Fi                           0.00  7.92     73
         Action, Adventure, Supernatural                     4.49  7.24      2
         Action, Avant Garde                                 5.04  5.04      1
         Action, Avant Garde, Comedy, Sci-Fi                 6.36  6.51      2
         Action, Avant Garde, Comedy, Supernatural, Ecchi    6.38  6.38      1
         Action, Avant Garde, Drama, Horror                  5.60  5.60      1
         Action, Avant Garde, Drama, Sci-Fi                  6.31  6.31      1
         Action, Avant Garde, Horror, Sci-Fi                 5.94  5.94      1
         Action, Avant Garde, Sci-Fi                         0.00  0.00      2
         Action, Award Winning                               8.18  8.18      1
         Action, Award Winning, Comedy                       5.24  6.16      2
         Action, Award Winning, Drama                        0.00  5.65      3
         Action, Award Winning, Drama, Mystery               7.85  7.85      1
         Action, Award Winning, Drama, Sci-Fi                6.73  8.00      5
         Action, Award Winning, Drama, Sci-Fi, Suspense      8.61  8.61      1
         Action, Award Winning, Mystery, Sci-Fi              7.43  7.43      1
         Action, Award Winning, Mystery, Sci-Fi, Suspense    8.27  8.27      1
         Action, Award Winning, Romance, Sci-Fi              7.94  7.94      1
         Action, Award Winning, Sci-Fi                       0.00  0.00      1
         Action, Award Winning, Supernatural                 6.49  6.49      1
         Action, Boys Love, Comedy, Fantasy, Mystery, Su...  6.78  6.78      1
         Action, Boys Love, Drama, Erotica                   6.86  6.86      1
         Action, Boys Love, Drama, Supernatural              6.09  6.09      1
         Action, Boys Love, Fantasy, Supernatural            6.76  6.76      1
         Action, Boys Love, Horror, Sci-Fi, Supernatural     5.09  5.09      1
         Action, Boys Love, Sci-Fi, Hentai                   5.40  5.40      1
         Action, Comedy                                      0.00  8.16     72
         Action, Comedy, Drama                               0.00  7.51      5
         Action, Comedy, Drama, Fantasy                      7.57  7.57      1
         Action, Comedy, Drama, Fantasy, Romance             7.44  7.44      1
         Action, Comedy, Drama, Fantasy, Slice of Life       6.40  6.40      1
         Action, Comedy, Drama, Mystery                      7.31  7.85      3
         Action, Comedy, Drama, Romance                      6.55  7.34      2
         Action, Comedy, Drama, Sci-Fi                       5.82  9.04      4
         Action, Comedy, Drama, Sports                       6.22  7.15      2
         Action, Comedy, Ecchi                               5.26  6.80      6
         Action, Comedy, Erotica                             4.64  4.64      1
         Action, Comedy, Fantasy                             0.00  8.27     26
         Action, Comedy, Fantasy, Ecchi                      6.03  6.80      2
         Action, Comedy, Fantasy, Horror, Supernatural       6.44  6.44      1
         Action, Comedy, Fantasy, Mystery                    0.00  0.00      1
         Action, Comedy, Fantasy, Romance, Ecchi             7.25  7.34      3
         Action, Comedy, Fantasy, Romance, Sci-Fi            5.29  5.29      1
         Action, Comedy, Fantasy, Sci-Fi                     0.00  7.52      3
         Action, Comedy, Fantasy, Sci-Fi, Ecchi              5.88  5.88      1
         Action, Comedy, Girls Love, Ecchi                   4.00  6.51      4
         Action, Comedy, Hentai                              5.15  5.39      2
         Action, Comedy, Horror, Supernatural                6.95  6.95      1
         Action, Comedy, Mystery                             4.81  7.86     15
         Action, Comedy, Mystery, Romance                    6.76  6.76      1
         Action, Comedy, Mystery, Supernatural               7.19  8.25      2
         Action, Comedy, Romance                             0.00  7.74      4
         Action, Comedy, Romance, Ecchi                      6.93  7.42      2
         Action, Comedy, Romance, Sci-Fi                     7.02  7.41      2
         Action, Comedy, Romance, Sci-Fi, Ecchi              5.74  5.74      1
         Action, Comedy, Romance, Supernatural, Ecchi        5.58  5.58      1
         Action, Comedy, Romance, Supernatural, Hentai       4.66  4.66      1
         Action, Comedy, Sci-Fi                              0.00  8.91     35

In [21]:
df[['Score', 'Popularity', 'Favorites', 'Members']].corr()

               Score  Popularity  Favorites   Members
Score       1.000000   -0.804557   0.127762  0.261196
Popularity -0.804557    1.000000  -0.163173 -0.363865
Favorites   0.127762   -0.163173   1.000000  0.773120
Members     0.261196   -0.363865   0.773120  1.000000

In [22]:
df.groupby('Type')['Score'].describe()

          count      mean       std  min   25%    50%   75%   max
Type
Movie    4381.0  3.584054  3.253007  0.0  0.00  4.950  6.55  9.04
Music    2686.0  3.236247  2.968803  0.0  0.00  4.935  5.88  8.85
ONA      3533.0  3.296833  3.076853  0.0  0.00  4.930  6.08  8.72
OVA      4076.0  5.007910  2.572711  0.0  5.04  5.960  6.64  9.02
Special  2558.0  5.074156  2.650851  0.0  5.15  6.140  6.74  9.05
TV       7597.0  4.039608  3.425916  0.0  0.00  6.020  7.04  9.10
UNKNOWN    74.0  0.082162  0.706786  0.0  0.00  0.000  0.00  6.08